# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ric_j\OneDrive\Projects\FINISHZZ\arenavision_ui\ui\arenavision_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("ArenaVision")
        main_window.setEnabled(True)
        main_window.resize(1387, 883)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.todos_jogos = QtWidgets.QPushButton(self.centralwidget)
        self.todos_jogos.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.todos_jogos.setObjectName("todos_jogos")
        self.procurar_jogo_texto = QtWidgets.QLineEdit(self.centralwidget)
        self.procurar_jogo_texto.setGeometry(QtCore.QRect(220, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.procurar_jogo_texto.setFont(font)
        self.procurar_jogo_texto.setObjectName("procurar_jogo_texto")
        self.procurar_jogo = QtWidgets.QPushButton(self.centralwidget)
        self.procurar_jogo.setGeometry(QtCore.QRect(640, 10, 161, 41))
        self.procurar_jogo.setObjectName("procurar_jogo")
        self.table_jogos = QtWidgets.QTableWidget(self.centralwidget)
        self.table_jogos.setGeometry(QtCore.QRect(0, 50, 1381, 791))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.table_jogos.setFont(font)
        self.table_jogos.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.table_jogos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_jogos.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table_jogos.setLineWidth(2)
        self.table_jogos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.table_jogos.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.table_jogos.setTabKeyNavigation(False)
        self.table_jogos.setProperty("showDropIndicator", False)
        self.table_jogos.setDragDropOverwriteMode(False)
        self.table_jogos.setAlternatingRowColors(True)
        self.table_jogos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_jogos.setGridStyle(QtCore.Qt.DashLine)
        self.table_jogos.setWordWrap(False)
        self.table_jogos.setCornerButtonEnabled(True)
        self.table_jogos.setRowCount(0)
        self.table_jogos.setObjectName("table_jogos")
        self.table_jogos.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.table_jogos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_jogos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_jogos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_jogos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_jogos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_jogos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_jogos.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(950, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.select_days = QtWidgets.QComboBox(self.centralwidget)
        self.select_days.setGeometry(QtCore.QRect(1010, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.select_days.setFont(font)
        self.select_days.setObjectName("select_days")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1387, 31))
        self.menubar.setObjectName("menubar")
        self.menuOp_es = QtWidgets.QMenu(self.menubar)
        self.menuOp_es.setObjectName("menuOp_es")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.actionrecome_ar = QtWidgets.QAction(main_window)
        self.actionrecome_ar.setObjectName("actionrecome_ar")
        self.actionSair = QtWidgets.QAction(main_window)
        self.actionSair.setObjectName("actionSair")
        self.menuOp_es.addAction(self.actionrecome_ar)
        self.menuOp_es.addAction(self.actionSair)
        self.menubar.addAction(self.menuOp_es.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.todos_jogos.setText(_translate("main_window", "TODOS OS JOGOS"))
        self.procurar_jogo.setText(_translate("main_window", "PROCURAR JOGO"))
        self.table_jogos.setSortingEnabled(True)
        item = self.table_jogos.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "Horas"))
        item = self.table_jogos.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Tipo de Jogo"))
        item = self.table_jogos.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Liga"))
        item = self.table_jogos.horizontalHeaderItem(3)
        item.setText(_translate("main_window", "Equipas"))
        item = self.table_jogos.horizontalHeaderItem(4)
        item.setText(_translate("main_window", "Língua"))
        item = self.table_jogos.horizontalHeaderItem(5)
        item.setText(_translate("main_window", "Canal 1"))
        item = self.table_jogos.horizontalHeaderItem(6)
        item.setText(_translate("main_window", "Canal 2"))
        self.label.setText(_translate("main_window", "DIA:"))
        self.menuOp_es.setTitle(_translate("main_window", "Opções"))
        self.actionrecome_ar.setText(_translate("main_window", "Recomeçar"))
        self.actionSair.setText(_translate("main_window", "Sair"))

